Miguel/ava 185 deploy devnet using ansible
maticnetwork/avail-deployment pull request #17
Opened 2022-05-12 09:48 UTC by MiguelDD1

Add ansible deployment.

2022-05-18 09:43 UTC, vcastellm requested changes

2022-05-18 09:43 UTC, vcastellm commented on ansible/roles/pre/tasks/aws_security_group.yml
> +- hosts: localhost
Infra should be handled from Terraform

2022-05-18 09:43 UTC, vcastellm commented on ansible/roles/pre/tasks/main.yml
> +- import_playbook: setup_security_group.yml
Infra from Terraform ideally.

2022-05-18 09:43 UTC, vcastellm commented on ansible/roles/pre/tasks/main.yml
> +- import_playbook: setup_docker.yml
Ideally all instance dependencies should be handled in the cloud-init script in the at instance start.

2022-05-18 09:43 UTC, vcastellm commented on ansible/roles/pre/tasks/main.yml
> +- import_playbook: setup_vault.yml
Secrets management should come from the secrets management infra provided by DevOps/Infra.

2022-05-18 09:43 UTC, vcastellm commented on ansible/roles/validators/.travis.yml
> +---
Are we using Travis?

2022-05-18 09:43 UTC, vcastellm commented on ansible/roles/validators/.travis.yml
> +  webhooks: https://galaxy.ansible.com/api/v1/notifications/
missing new line

2022-05-18 09:43 UTC, vcastellm commented on ansible/scripts/close_ssh_port.fish
> +#!/usr/bin/fish
What's the purpose of this scripts?

2022-05-18 09:43 UTC, vcastellm commented on ansible/site.yml
> +            - /ip4/15.237.127.118/tcp/30333/p2p/12D3KooWQtxig5HukFDwQzshGWgQEZAqGqdCN7AQBW7cQRJWCyxL
Could we work with domains instead of IPs?

2022-05-18 09:43 UTC, vcastellm commented on ansible/inventory.yaml
> +all:
We should use dynamic inventory

2022-05-18 09:43 UTC, vcastellm commented on ansible/roles/bootnodes/.travis.yml
> +  webhooks: https://galaxy.ansible.com/api/v1/notifications/
Missing new line

2022-05-18 09:43 UTC, vcastellm commented on ansible/roles/validators/templates/da.sh
> +#!/bin/bash
Instead of running with a script mounted in a volume, can we use actual params when calling the container?

2022-05-27 12:58 UTC, praetoriansentry commented on ansible/roles/bootnode/tasks/main.yml
> +      com.datadoghq.ad.instances: '[{"openmetrics_endpoint":"http://%%host%%:9615/metrics", "namespace": "avail", "metrics": ["substrate*"]}]'
Glad this works. Any reason for not using the variables `prometheus.port` and `prometheus.endpoint`

2022-05-27 12:58 UTC, praetoriansentry commented on ansible/roles/bootnode/tasks/main.yml
> +      DA_CHAIN: "/da/genesis/testnet-v2.chain.spec.raw.json"
I think when we refactor the dockerfile, we can drop these env variables and also bundle the final chainspec

2022-05-27 12:58 UTC, praetoriansentry commented on ansible/roles/validators/tasks/load_key.yml
> +- name: "load {{key_type}} private key into {{container}}"
I didn't realize we had this. It would be useful to use in the bootnode as wel.

2022-05-27 12:58 UTC, praetoriansentry commented on docker-compose.local.testnet.yml
> +      - ./ansible/roles/bootnode/templates/genesis:/da/genesis:ro
Since we moved this - I'll need to update this location and probably dynamically generate the chainspec

2022-05-27 12:58 UTC, praetoriansentry commented on ansible/roles/validators/tasks/main.yml
> +    image: 0xpolygon/avail:ava-154
This should probably be `1.0.0`?

2022-05-27 13:46 UTC, praetoriansentry approved these changes
lgtm we can address validator mismatch in separate PR

2022-05-27 13:48 UTC, vcastellm commented on ansible/roles/bootnode/tasks/main.yml
> +      com.datadoghq.ad.instances: '[{"openmetrics_endpoint":"http://%%host%%:9615/metrics", "namespace": "avail", "metrics": ["substrate*"]}]'
yeah, it's somewhat tricky to construct this kind of strings in Ansible with Jinja... we can try in another PR

2022-05-27 13:48 UTC, vcastellm commented on ansible/roles/bootnode/tasks/main.yml
> +      DA_CHAIN: "/da/genesis/testnet-v2.chain.spec.raw.json"
TRUE

2022-05-27 13:49 UTC, vcastellm commented on docker-compose.local.testnet.yml
> +      - ./ansible/roles/bootnode/templates/genesis:/da/genesis:ro
Let's do that in another PR

2022-05-27 14:06 UTC, vcastellm commented on ansible/roles/validators/tasks/main.yml
> +    image: 0xpolygon/avail:ava-154
yes, next PR

2022-05-27 14:07 UTC, merged